   <nav>
     <ul>
        <li><a class="button button-primary" href="index.php">Home</a></li>
        <li><a class="button button-primary" href="chinese-foods.php">Chinese Food</a></li>
        <li><a class="button button-primary" href="italian-foods.php">Italian Food</a></li>
        <li><a class="button button-primary" href="north-american-foods.php">North American Food</a></li>
	<li><a class="button button-primary" href="colophon.php">Colophon</li>
      </ul>
    </nav>