   <nav>
     <ul>
        <li><a class="button button-primary" href="index.html">Home</a></li>
        <li><a class="button button-primary" href="chinese-foods.html">Chinese Food</a></li>
        <li><a class="button button-primary" href="italian-foods.html">Italian Food</a></li>
        <li><a class="button button-primary" href="north-american-foods.html">North American Food</a></li>
      </ul>
    </nav>